[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  port = 8888

# Function redirects
[[redirects]]
  from = "/admin/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/admin/api/check-session"
  to = "/.netlify/functions/check-session"
  status = 200

[[redirects]]
  from = "/api/add-player"
  to = "/.netlify/functions/add-player"
  status = 200

[[redirects]]
  from = "/api/players"
  to = "/.netlify/functions/api-players"
  status = 200

[[redirects]]
  from = "/admin/api/players"
  to = "/.netlify/functions/players"
  status = 200

[[redirects]]
  from = "/admin/save-players"
  to = "/.netlify/functions/save-players"
  status = 200

[[redirects]]
  from = "/api/masterlist"
  to = "/.netlify/functions/masterlist"
  status = 200

[[redirects]]
  from = "/admin/api/masterlist"
  to = "/.netlify/functions/masterlist"
  status = 200

[[redirects]]
  from = "/api/registration"
  to = "/.netlify/functions/registration"
  status = 200

[[redirects]]
  from = "/admin/api/admin-users"
  to = "/.netlify/functions/admin-users"
  status = 200

[[redirects]]
  from = "/admin/api/registration-sessions"
  to = "/.netlify/functions/registration-sessions"
  status = 200

[[redirects]]
  from = "/api/get-registration-session"
  to = "/.netlify/functions/get-registration-session"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables
[context.production.environment]
  NODE_ENV = "production" 