[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[dev]
  command = "npm start"
  port = 3001

# Redirect all requests to the serverless function
[[redirects]]
  from = "/admin/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/admin/api/check-session"
  to = "/.netlify/functions/check-session"
  status = 200

[[redirects]]
  from = "/admin/api/players"
  to = "/.netlify/functions/players"
  status = 200

[[redirects]]
  from = "/admin/api/masterlist"
  to = "/.netlify/functions/masterlist"
  status = 200

[[redirects]]
  from = "/admin/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/api/players"
  to = "/.netlify/functions/api-players"
  status = 200

[[redirects]]
  from = "/api/add-player"
  to = "/.netlify/functions/add-player"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"

# Environment variables
[context.production.environment]
  NODE_ENV = "production" 